
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'leftMASMENOSleftPORDIVIDIDOrightPOTENCIArightUMINUSDIVIDIDO MAS MENOS NUMERO PARENTESISDER PARENTESISIZQ POR POTENCIAexpression : expression MAS expression\n                  | expression MENOS expression\n                  | expression POR expression\n                  | expression DIVIDIDO expression\n                  | expression POTENCIA expressionexpression : MENOS expression %prec UMINUSexpression : NUMEROexpression : PARENTESISIZQ expression PARENTESISDER'
    
_lr_action_items = {'MENOS':([0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,],[2,6,2,-7,2,2,2,2,2,2,-6,6,-1,-2,-3,-4,-5,-8,]),'NUMERO':([0,2,4,5,6,7,8,9,],[3,3,3,3,3,3,3,3,]),'PARENTESISIZQ':([0,2,4,5,6,7,8,9,],[4,4,4,4,4,4,4,4,]),'$end':([1,3,10,12,13,14,15,16,17,],[0,-7,-6,-1,-2,-3,-4,-5,-8,]),'MAS':([1,3,10,11,12,13,14,15,16,17,],[5,-7,-6,5,-1,-2,-3,-4,-5,-8,]),'POR':([1,3,10,11,12,13,14,15,16,17,],[7,-7,-6,7,7,7,-3,-4,-5,-8,]),'DIVIDIDO':([1,3,10,11,12,13,14,15,16,17,],[8,-7,-6,8,8,8,-3,-4,-5,-8,]),'POTENCIA':([1,3,10,11,12,13,14,15,16,17,],[9,-7,-6,9,9,9,9,9,9,-8,]),'PARENTESISDER':([3,10,11,12,13,14,15,16,17,],[-7,-6,17,-1,-2,-3,-4,-5,-8,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expression':([0,2,4,5,6,7,8,9,],[1,10,11,12,13,14,15,16,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expression","S'",1,None,None,None),
  ('expression -> expression MAS expression','expression',3,'p_expression_binop','calcparse.py',14),
  ('expression -> expression MENOS expression','expression',3,'p_expression_binop','calcparse.py',15),
  ('expression -> expression POR expression','expression',3,'p_expression_binop','calcparse.py',16),
  ('expression -> expression DIVIDIDO expression','expression',3,'p_expression_binop','calcparse.py',17),
  ('expression -> expression POTENCIA expression','expression',3,'p_expression_binop','calcparse.py',18),
  ('expression -> MENOS expression','expression',2,'p_expression_uminus','calcparse.py',39),
  ('expression -> NUMERO','expression',1,'p_expression_numero','calcparse.py',43),
  ('expression -> PARENTESISIZQ expression PARENTESISDER','expression',3,'p_expression_parentheses','calcparse.py',47),
]
